/**
 * Markdown report generator.
 *
 * Renders a {@link DiagnosisReport} into a shareable Markdown document.
 *
 * @module dsh-tianshu-analyzer/report/markdown
 */

import type { DiagnosisReport, Finding, Severity } from '../types.ts'

const SEVERITY_EMOJI: Readonly<Record<Severity, string>> = {
  critical: '🔴',
  major: '🟠',
  minor: '🟡',
}

/** Render a full diagnosis report as Markdown. */
export function renderMarkdown(report: DiagnosisReport): string {
  const lines: string[] = []
  lines.push(`# TianShu Failure Diagnosis Report`)
  lines.push('')
  lines.push(`| field | value |`)
  lines.push(`|---|---|`)
  lines.push(`| session | \`${report.sessionId}\` |`)
  lines.push(`| analyzed at | ${report.analyzedAt} |`)
  if (report.triggerReason !== null) lines.push(`| trigger reason | \`${report.triggerReason}\` |`)
  if (report.route !== null) lines.push(`| model route | ${report.route.provider}/${report.route.model} |`)
  lines.push(`| events | ${report.stats.totalEvents} |`)
  lines.push(`| turns | ${report.stats.totalTurns} |`)
  lines.push(`| tool calls | ${report.stats.totalToolCalls} (errors: ${report.stats.totalToolErrors}) |`)
  lines.push(`| tokens | in ${report.stats.totalInputTokens} / out ${report.stats.totalOutputTokens} |`)
  if (report.stats.durationMs !== null) lines.push(`| duration | ${formatDuration(report.stats.durationMs)} |`)
  lines.push('')

  // --- Findings ---
  lines.push(`## Findings (${report.findings.length})`)
  lines.push('')
  if (report.findings.length === 0) {
    lines.push('_No failure patterns detected by the rule engine._')
    lines.push('')
  } else {
    for (const [i, f] of report.findings.entries()) {
      lines.push(renderFinding(i + 1, f))
    }
  }

  // --- Heatmap ---
  if (report.heatmap.length > 0) {
    lines.push(`## Tool call heat map`)
    lines.push('')
    lines.push(`| tool | calls | errors | first seq | last seq |`)
    lines.push(`|---|---:|---:|---:|---:|`)
    for (const h of report.heatmap) {
      lines.push(`| \`${h.name}\` | ${h.calls} | ${h.errors} | ${h.firstSeq} | ${h.lastSeq} |`)
    }
    lines.push('')
  }

  // --- Fork points ---
  if (report.forkPoints.length > 0) {
    lines.push(`## Recommended fork points`)
    lines.push('')
    for (const [i, fp] of report.forkPoints.entries()) {
      lines.push(`### ${i + 1}. Fork at seq ${fp.seq}`)
      lines.push(`> ${fp.rationale}`)
      lines.push('')
      lines.push(`**Try instead:** ${fp.tryInstead}`)
      lines.push('')
    }
  }

  // --- LLM diagnosis ---
  if (report.llmDiagnosis !== null) {
    lines.push(`## LLM deep diagnosis`)
    lines.push('')
    lines.push(report.llmDiagnosis)
    lines.push('')
  } else if (report.llmDiagnosisError !== null) {
    lines.push(`## LLM deep diagnosis`)
    lines.push('')
    lines.push(`_LLM diagnosis was enabled but failed: ${report.llmDiagnosisError}_`)
    lines.push('')
  }

  lines.push('---')
  lines.push('_Generated by [TianShu (天枢)](https://github.com/) — dsh-tianshu-analyzer_')
  return lines.join('\n')
}

/** Render a single finding as a Markdown subsection. */
function renderFinding(index: number, f: Finding): string {
  const lines: string[] = []
  lines.push(`### ${SEVERITY_EMOJI[f.severity]} ${index}. \`${f.mode}\` — ${f.headline}`)
  lines.push('')
  lines.push(f.detail)
  lines.push('')
  if (f.evidenceSeqs.length > 0) {
    lines.push(`**Evidence:** seqs ${f.evidenceSeqs.map(s => `\`${s}\``).join(', ')}`)
    lines.push('')
  }
  lines.push(`**Suggested fix:** ${f.suggestion}`)
  lines.push('')
  return lines.join('\n')
}

/** Format a millisecond duration as a human-readable string. */
function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)}s`
  const m = Math.floor(ms / 60_000)
  const s = Math.round((ms % 60_000) / 1000)
  return `${m}m${s}s`
}
